
services:
  app:
    container_name: article-gin-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - /app/tmp
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - gateway_dev-net

  mongo:
    container_name: article-mongo
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    networks:
      - gateway_dev-net

volumes:
  mongo_data:

networks:
  gateway_dev-net:
    external: true